name: Setup & build calm-dsl
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.7', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: black
      uses: psf/black@stable # Exclude list is not honored - https://github.com/psf/black/issues/1584
      with:
        version: "22.3.0"
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Install requirements in Python ${{ matrix.python-version }}
      run: |
        make dev
    - name: Execute calm in Python ${{ matrix.python-version }}
      run: |
        source venv/bin/activate
        calm
    - name: Build python package in Python ${{ matrix.python-version }}
      run: |
        make dist
    - name: Build docker image in Python ${{ matrix.python-version }}
      run: |
        make docker
    - name: Execute container in Python ${{ matrix.python-version }}
      uses: addnab/docker-run-action@v3
      with:
        image: ntnx/calm-dsl
        run: calm
    - name: Publish docker image
      if: ${{ github.event_name == 'push' && github.repository == 'nutanix/calm-dsl'}}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ntnx/calm-dsl
