name: Create a Jira ticket for Github issue
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Print issue body
        run: echo "${{ github.event.issue.html_url }}"\
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.body }}
      